version: '3.9'

services:
  identity-db:
    image: 'mongo'
    container_name: 'identity-db'
    environment:
      - MONGO_INITDB_DATABASE=identitydb
      - MONGO_INITDB_ROOT_USERNAME=identityrootuser
      - MONGO_INITDB_ROOT_PASSWORD=identityrootpass
    ports:
      - '27017:27017'
    volumes:
      - ../migrations/mongo/mongo-db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - identity-db-volume:/data/db

volumes:
  identity-db-volume:
